name: Godot Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Godot Project
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Generate Debug Keystore
        run: |
          mkdir -p ~/.android
          keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      - name: Configure Godot Editor Settings
        run: |
          mkdir -vp ~/.config/godot
          echo '[resource]' > ~/.config/godot/editor_settings-4.tres
          echo 'export/android/android_sdk_path = "/usr/lib/android-sdk"' >> ~/.config/godot/editor_settings-4.tres
          echo 'export/android/debug_keystore = "/root/.android/debug.keystore"' >> ~/.config/godot/editor_settings-4.tres
          echo 'export/android/debug_keystore_user = "androiddebugkey"' >> ~/.config/godot/editor_settings-4.tres
          echo 'export/android/debug_keystore_pass = "android"' >> ~/.config/godot/editor_settings-4.tres

      - name: Prepare Build Directory
        run: mkdir -v -p build/android

      - name: Godot Export
        run: |
          godot --headless --export-debug "Android" build/android/ROAD.apk

      - name: Zip Build Output
        run: |
          cd build/android && zip -r ../../Android.zip .

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Build
          path: Android.zip

  deploy:
    name: Deploy to Itch.io
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: Android-Build
          path: .

      - name: Deploy to Itch.io using Butler
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: android
          ITCH_GAME: road
          ITCH_USER: ${{ secrets.ITCH_USERNAME }}
          PACKAGE: Android.zip
